name: dji_a_v5
description: "大疆Android v5"
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  # 生成
  pigeon: ^22.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.lianshi.dji_a_v5
        pluginClass: DjiAV5Plugin
      ios:
        pluginClass: DjiAV5Plugin
